name: Simple Test

on:
  workflow_dispatch:
    inputs:
      action_branch:
        description: The branch of the action to use
        default: main
        
      organization:
        description: The organization to process
        default: octodemo
        
      activity_days:
        description: The number of days to use to analyze activity
        default: '7'
        
      debug:
        description: Debug output
        default: 'false'

      timezone:
        description: The timezone to use for the report
        default: 'Asia/Bangkok'

jobs:
  analyze:
    name: Analyze Organization Activity
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.action_branch }}
        
      - name: Analyze organization
        id: analyze_org
        uses: ./
        with:
          token: ${{ secrets.OCTODEMO_TEMP_TOKEN }}
          organization: ${{ github.event.inputs.organization }}
          activity_days: ${{ github.event.inputs.activity_days }}
          debug: ${{ github.event.inputs.debug }}
          timezone: ${{ github.event.inputs.timezone }}
 
      - name: Attach Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            ${{ steps.analyze_org.outputs.report_csv }}
            ${{ steps.analyze_org.outputs.report_json }}
            ${{ steps.analyze_org.outputs.data_organization_user_activity }}
